spring:
  application:
    name: KanzoPizzaMsCustomer
  profiles:
    active: ${ACTIVE_PROFILE:dev}
    include:
      - common
      - db
      - security
      - client
  main:
    allow-bean-definition-overriding: true
